from gclib_common import GCLib


EXPORTS = [
    "gc_create",
    "gc_create_version",
    "gc_destroy",
    "gc_set_client_info",
    "gc_set_client_identity",
    "gc_set_handshake",
    "gc_set_encryption_certificate_pem",
    "gc_set_encryption_certificate_file",
    "gc_connect",
    "gc_login",
    "gc_disconnect",
    "gc_is_connected",
    "gc_is_authenticated",
    "gc_poll",
    "gc_get_last_error",
    "gc_get_player_json",
    "gc_get_self_player_json",
    "gc_set_resource_dump_directory",
    "gc_set_resource_dump_types",
    "gc_on_connected",
    "gc_on_disconnected",
    "gc_on_authenticated",
    "gc_on_raw_packet",
    "gc_on_packet_event",
    "gc_on_chat",
    "gc_on_chat_ex",
    "gc_on_private_message",
    "gc_on_level_name",
    "gc_on_player_warp",
    "gc_on_player_warp2",
    "gc_on_player_props",
    "gc_on_other_player_props",
    "gc_on_player_left",
    "gc_on_board_packet",
    "gc_on_file",
    "gc_on_file_failed",
    "gc_on_world_time",
    "gc_on_npc_props",
    "gc_on_npc_deleted",
    "gc_on_sign",
    "gc_on_explosion",
    "gc_on_hit_objects",
    "gc_on_server_text",
    "gc_on_flag_set",
    "gc_on_flag_del",
    "gc_on_weapon_script",
    "gc_on_resource",
    "gc_send_packet",
    "gc_send_chat",
    "gc_send_level_chat",
    "gc_send_toall_chat",
    "gc_set_player_prop_string",
    "gc_set_player_prop_byte",
    "gc_set_nickname",
    "gc_set_head_image",
    "gc_set_body_image",
    "gc_set_player_attribute",
    "gc_set_player_status",
    "gc_set_player_colors",
    "gc_move",
    "gc_walk_step",
    "gc_level_warp",
    "gc_set_animation",
    "gc_request_file",
    "gc_request_level_board",
    "gc_send_private_message",
    "gc_set_flag",
    "gc_unset_flag",
    "gc_request_text",
    "gc_send_text",
    "gc_request_weapon_script",
    "gc_request_class_script",
    "gc_request_gani_script",
    "gc_free_string",
]


if __name__ == "__main__":
    lib = GCLib().lib
    for name in EXPORTS:
        getattr(lib, name)
    print("exports ok")
